if(JSON.parse(localStorage.getItem("stores"))){
    return;
}
else{
    localStorage.setItem("stores", JSON.stringify([
        {
            value: "0",
            title: "Nike",
            category: "Shoes Shop",
            image: "assets/image/stores/store27.png",
            banner: "../../../assets/image/stores/nike-background.jpg",
            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],
            products: [
                {
                    value: 0,
                    image: "https://iili.io/HkeiZmb.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 1,
                    image: "https://iili.io/HkeiQku.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 2,
                    image: "https://iili.io/Hkeis29.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 3,
                    image: "https://iili.io/HkeiL7e.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 4,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 5,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 6,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 7,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 8,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 9,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 10,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 11,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],

        },

        {
            value: "1",
            title: "SS Beauty Shop",
            category: "Beauty Shop",
            image: "assets/image/stores/store1.jpeg",
            banner: "../../../assets/image/stores/ss-beauty/ss-beauty-background.webp",

            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],
            products: [
                {
                    value: 12,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 13,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 14,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 15,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 16,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 17,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 18,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 19,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 20,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 21,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 22,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 23,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },],
        },

        {
            value: "2",
            title: "Lenskart",
            category: "Specse Shop",
            image: "assets/image/stores/store42.jpg",
            banner: "../../../assets/image/stores/lenskart/glass-background.jpg",
            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],

            products: [
                {
                    value: 24,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 25,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 26,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 27,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 28,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 29,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 30,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 31,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 32,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 33,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 34,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 35,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
            ]
        },

        {
            value: "3",
            title: "Chales & Keith",
            category: "Bags & Luggage",
            image: "assets/image/stores/store2.png",
            banner: "../../../assets/image/stores/Charles-Keith/banner.png",
            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],
            products: [
                {
                    value: 36,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 37,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 38,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 39,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 40,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 41,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 42,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 43,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 44,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 45,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 46,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 47,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
            ]
        },

        {
            value: "4",
            name: "Vero Moda",
            category: "Fashion Dress For Women",
            image: "assets/image/stores/store3.png",
            banner: "../../../assets/image/stores/vero-moda/fashion-dress-women-banner.gif",
            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],

            products: [
                {
                    value: 48,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 49,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 50,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 51,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 52,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 53,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 54,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 55,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 56,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 57,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 58,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 59,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        },

        {
            value: "5",
            name: "Poorvika",
            category: "Mobile Shop",
            image: "assets/image/stores/store52.png",
            banner: "../../../assets/image/stores/ivenus/mobile-banner.jpg",
            brand_img: [
                {
                    img: "../../../assets/image/stores/ivenus/mi-logo.png",
                    name: "mi"
                },
                {
                    img: "../../../assets/image/stores/ivenus/oppo-logo.png",
                    name: "oppo"
                },
                {
                    img: "../../../assets/image/stores/ivenus/realme-logo.png",
                    name: "realme",
                },
                {
                    img: "../../../assets/image/stores/ivenus/vivo-logo.svg",
                    name: "vivo",
                },
                {
                    img: "../../../assets/image/stores/ivenus/samsung-logo.png",
                    name: "samsung",
                },
            ],

            products: [
                {
                    value: 60,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 61,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 62,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 63,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 64,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 65,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 66,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 67,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 68,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 69,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 70,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 71,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        
        },

        {
            value: "6",
            name: "MAC",
            category: "Beauty Products",
            image: "assets/image/stores/store34.gif",
            banner: "../../../assets/image/stores/mac/banner4.png",
            brand_img: [
                {
                    img: "../../../assets/image/stores/ivenus-apple/moblies-apple.png",
                    name: "iPhone"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/ipad-pro.png",
                    name: "iPad"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/airbots.png",
                    name: "AirPods",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/AirTag.png",
                    name: "AirTag",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/mac.png",
                    name: "Mac",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/Apple-watch.png",
                    name: "iWatch"
                },
            ],
            products: [
                {
                    value: 72,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 73,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 74,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 75,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 76,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 77,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 78,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 79,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 80,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 81,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 82,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 83,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        
            
        },

        {
            value: "7",
            title: "Jack & Zone",
            category: "Mens Fashion",
            image: "assets/image/stores/store4.png",
            banner: "../../../assets/image/stores/jack-zone/mens-fashion-banner.png",
            brand_img: [
                {
                    img: "../../../assets/image/stores/ivenus-apple/moblies-apple.png",
                    name: "iPhone"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/ipad-pro.png",
                    name: "iPad"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/airbots.png",
                    name: "AirPods",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/AirTag.png",
                    name: "AirTag",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/mac.png",
                    name: "Mac",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/Apple-watch.png",
                    name: "iWatch"
                },
            ],
            products: [
                {
                    value: 84,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 85,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 86,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 87,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 88,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 89,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 90,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 91,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 92,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 93,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 94,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 95,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        
        },

        {
            value: "8",
            title: "Label Ritu Kumar",
            category: "Designer Wear",
            image: "assets/image/stores/store9.jpg",
            banner: "../../../assets/image/stores/label-designer-wear/banner.png",
            brand_img: [
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: ""
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: "",
                },
                {
                    img: "",
                    name: ""
                },
            ],
            products: [
                {
                    value: 96,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 97,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 98,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 99,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 100,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 101,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 102,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 103,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 104,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 105,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 106,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 107,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        
        },

        {
            value: "9",
            title: "ivenus",
            category: "Apple Premium Reseller",
            image: "assets/image/stores/store18.jpeg",
            banner: "../../../assets/image/stores/ivenus-apple/banner.png",
            brand_img: [
                {
                    img: "../../../assets/image/stores/ivenus-apple/moblies-apple.png",
                    name: "iPhone"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/ipad-pro.png",
                    name: "iPad"
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/airbots.png",
                    name: "AirPods",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/AirTag.png",
                    name: "AirTag",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/mac.png",
                    name: "Mac",
                },
                {
                    img: "../../../assets/image/stores/ivenus-apple/Apple-watch.png",
                    name: "iWatch"
                },
            ],
            products: [
                {
                    value: 108,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Air Zoom Vomero 15 Running Shoe",
                    price: "₹6000",
                    full_price: "₹10000",
                    discount: "(40% off)",
                    rating: "4.5",
                    reviews: "( 2023 ) Reviews",
                },
                {
                    value: 109,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Ultra Light Running and Training Shoes",
                    price: "₹1518",
                    full_price: "₹2999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 3366 ) Reviews",
                },
                {
                    value: 110,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Running Shoe Bacca Bucci",
                    price: "₹1329",
                    full_price: "₹2999",
                    discount: "(56% off)",
                    rating: "4.3",
                    reviews: "( 2470 ) Reviews",
                },
                {
                    value: 111,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Slip-on Premium Comfy-fit Sneaker",
                    price: "₹1000",
                    full_price: "₹2000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 2229 ) Reviews",
                },
                {
                    value: 112,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹1999",
                    full_price: "₹3299",
                    discount: "(39% off)",
                    rating: "4.2",
                    reviews: "( 1290 ) Reviews",
                },
                {
                    value: 113,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Mens Ultimate Ease Range Walking Shoe",
                    price: "₹1239",
                    full_price: "₹1499",
                    discount: "(18% off)",
                    rating: "3.9",
                    reviews: "( 4238 ) Reviews",
                },
                {
                    value: 114,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Wonder-13 Sports Running Shoes",
                    price: "₹2000",
                    full_price: "₹4000",
                    discount: "(50% off)",
                    rating: "4.7",
                    reviews: "( 1234 ) Reviews",
                },
                {
                    value: 115,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "ASIAN Delta-20 Sports Running Walking",
                    price: "₹1500",
                    full_price: "₹3000",
                    discount: "(50% off)",
                    rating: "4.5",
                    reviews: "( 1908 ) Reviews",
                },
                {
                    value: 116,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Flash Shoe Badminton Shoes for Mens",
                    price: "₹3064",
                    full_price: "₹6000",
                    discount: "(43% off)",
                    rating: "4.1",
                    reviews: "( 3193 ) Reviews",
                },
                {
                    value: 117,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Men's Cosko Sports Running, Walking,Gym",
                    price: "₹1499",
                    full_price: "₹4000",
                    discount: "(63% off)",
                    rating: "4.5",
                    reviews: "( 1208 ) Reviews",
                },
                {
                    value: 118,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Crystal-13 Sports Running Walking Shoes",
                    price: "₹1249",
                    full_price: "₹2299",
                    discount: "(46% off)",
                    rating: "4.3",
                    reviews: "( 6009 ) Reviews",
                },
                {
                    value: 119,
                    image: "https://iili.io/HkeiDIj.webp",
                    title: "Skypee-31 Running Shoes,Walking Shoes",
                    price: "₹1999",
                    full_price: "₹4999",
                    discount: "(49% off)",
                    rating: "4.5",
                    reviews: "( 2317 ) Reviews",
                },
            ],
        
        }
        
    ]
))
}





